export default  dummyData = [
    {
        id: 1,
        date: new Date("2023-12-01"),
        category: "Electronics",
        status: "Delivered",
        quantity: 3,
        totalPrice: "$300",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "John Doe",
            description: "High-quality electronic gadget.",
            price: "$100",
            quantity: 3,
            totalPrice: "$300",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    // Add more dummy data as needed...
];