import { thumb1, thumb2, thumb3 } from "../../assets";

export default dummyData = [
    {
        id: 1,
        date: new Date("2023-12-01"),
        category: "Electronics",
        status: "Delivered",
        quantity: 3,
        totalPrice: "$300",
        details: {
            imageUrl: thumb1,
            customerName: "John Doe",
            description: "High-quality electronic gadget.",
            price: "$100",
            quantity: 3,
            totalPrice: "$300",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: thumb2,
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 3,
        date: new Date("2023-10-20"),
        category: "Home Goods",
        status: "Shipped",
        quantity: 5,
        totalPrice: "$150",
        details: {
            imageUrl: thumb3,
            customerName: "Alice Johnson",
            description: "Durable and stylish home essentials.",
            price: "$30",
            quantity: 5,
            totalPrice: "$150",
        },
    },
    {
        id: 4,
        date: new Date("2023-12-10"),
        category: "Books",
        status: "Delivered",
        quantity: 2,
        totalPrice: "$40",
        details: {
            imageUrl: thumb1,
            customerName: "Robert Brown",
            description: "Collection of best-selling novels.",
            price: "$20",
            quantity: 2,
            totalPrice: "$40",
        },
    },
    {
        id: 5,
        date: new Date("2023-12-05"),
        category: "Toys",
        status: "Pending",
        quantity: 4,
        totalPrice: "$120",
        details: {
            imageUrl: thumb2,
            customerName: "Lucy Green",
            description: "Fun and educational toys for kids.",
            price: "$30",
            quantity: 4,
            totalPrice: "$120",
        },
    },
    {
        id: 6,
        date: new Date("2023-11-25"),
        category: "Furniture",
        status: "Shipped",
        quantity: 1,
        totalPrice: "$250",
        details: {
            imageUrl: thumb3,
            customerName: "Tom Davis",
            description: "Modern and stylish furniture.",
            price: "$250",
            quantity: 1,
            totalPrice: "$250",
        },
    },
    {
        id: 7,
        date: new Date("2023-11-18"),
        category: "Appliances",
        status: "Pending",
        quantity: 2,
        totalPrice: "$500",
        details: {
            imageUrl: thumb1,
            customerName: "Sara Wilson",
            description: "Latest home appliances.",
            price: "$250",
            quantity: 2,
            totalPrice: "$500",
        },
    },
    {
        id: 8,
        date: new Date("2023-10-30"),
        category: "Gadgets",
        status: "Delivered",
        quantity: 3,
        totalPrice: "$450",
        details: {
            imageUrl: thumb2,
            customerName: "Chris Lee",
            description: "Advanced technology gadgets.",
            price: "$150",
            quantity: 3,
            totalPrice: "$450",
        },
    },
    {
        id: 9,
        date: new Date("2023-11-03"),
        category: "Accessories",
        status: "Pending",
        quantity: 5,
        totalPrice: "$75",
        details: {
            imageUrl: thumb3,
            customerName: "Megan White",
            description: "Fashionable accessories.",
            price: "$15",
            quantity: 5,
            totalPrice: "$75",
        },
    },
    {
        id: 10,
        date: new Date("2023-12-03"),
        category: "Stationery",
        status: "Shipped",
        quantity: 10,
        totalPrice: "$50",
        details: {
            imageUrl: thumb1,
            customerName: "Anna Black",
            description: "Stationery items for school.",
            price: "$5",
            quantity: 10,
            totalPrice: "$50",
        },
    },
];
