
import { thumb1 } from "../../assets";
import { thumb2 } from "../../assets";
import { thumb3 } from "../../assets";

export default  dummyData = [
    {
        id: 1,
        date: new Date("2023-12-01"),
        category: "Electronics",
        status: "Delivered",
        quantity: 3,
        totalPrice: "$300",
        details: {
            imageUrl: thumb1,
            customerName: "John Doe",
            description: "High-quality electronic gadget.",
            price: "$100",
            quantity: 3,
            totalPrice: "$300",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: thumb2,
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-10-02"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$150",
        details: {
            imageUrl: thumb3,
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$50",
            quantity: 3,
            totalPrice: "$150",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    {
        id: 2,
        date: new Date("2023-11-15"),
        category: "Clothing",
        status: "Pending",
        quantity: 2,
        totalPrice: "$80",
        details: {
            imageUrl: "https://via.placeholder.com/100",
            customerName: "Jane Smith",
            description: "Stylish and comfortable clothing.",
            price: "$40",
            quantity: 2,
            totalPrice: "$80",
        },
    },
    // Add more dummy data as needed...
];